// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMzB42-5uDNrDeBi7-HkEXk27l3I2bcA',
    appId: '1:237838703542:web:223c76feca092a107d7f17',
    messagingSenderId: '237838703542',
    projectId: 'zegocalltest-8e17b',
    authDomain: 'zegocalltest-8e17b.firebaseapp.com',
    storageBucket: 'zegocalltest-8e17b.appspot.com',
    measurementId: 'G-WD97T944SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuezyA0VJleylh95SZgDCjTriUoi1O1lU',
    appId: '1:237838703542:android:ad33aa07aed57d117d7f17',
    messagingSenderId: '237838703542',
    projectId: 'zegocalltest-8e17b',
    storageBucket: 'zegocalltest-8e17b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4O-zIbu3m5GmK-ysJVpIyAlXfumjBteo',
    appId: '1:237838703542:ios:616ad52d53b3a12c7d7f17',
    messagingSenderId: '237838703542',
    projectId: 'zegocalltest-8e17b',
    storageBucket: 'zegocalltest-8e17b.appspot.com',
    iosBundleId: 'com.zegocloudtest.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4O-zIbu3m5GmK-ysJVpIyAlXfumjBteo',
    appId: '1:237838703542:ios:c37a9ea5c78a02257d7f17',
    messagingSenderId: '237838703542',
    projectId: 'zegocalltest-8e17b',
    storageBucket: 'zegocalltest-8e17b.appspot.com',
    iosBundleId: 'com.zegocloudtest.app.RunnerTests',
  );
}
